In [2]:
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
#load in data frame
df = pd.read_csv('data/raw/combined_raw.csv')
df.head()

,university,id,webPublicationDate,sectionId,sectionName,webTitle,wordcount
0,University of Birmingham,theguardian/2010/jan/03/simonedebeauvoir-oxfor...,2010-01-03T18:36:43Z,global,Global,Elizabeth Fallaize obituary,1007
1,University of Birmingham,education/2010/jan/19/gel-curb-appetite-scient...,2010-01-19T00:05:05Z,education,Education,Food scientists develop appetite-curbing gel,839
2,University of Birmingham,science/2010/jan/25/mary-english-obituary,2010-01-25T18:38:39Z,science,Science,Mary English obituary,931
3,University of Birmingham,science/video/2010/feb/03/good-guys-draw-faste...,2010-02-03T04:50:00Z,science,Science,Video: Why the good guys draw faster in a gunf...,0
4,University of Birmingham,education/2010/feb/06/cv-clinic-jenny-adams,2010-02-06T00:05:03Z,education,Education,CV Clinic,552

In [4]:
#checks
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25142 entries, 0 to 25141
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   university          25142 non-null  object
 1   id                  25142 non-null  object
 2   webPublicationDate  25142 non-null  object
 3   sectionId           25142 non-null  object
 4   sectionName         25142 non-null  object
 5   webTitle            25142 non-null  object
 6   wordcount           25142 non-null  int64
dtypes: int64(1), object(6)
memory usage: 1.3+ MB

In [5]:
#checks
df['sectionName'].value_counts()

sectionName
Education                              3623
World news                             3289
Science                                2601
Society                                2303
Environment                            1735
                                       ...
Griffith University: Make it matter       1
Guardian green jobs                       1
Forward Women                             1
Help                                      1
Professional supplements                  1
Name: count, Length: 105, dtype: int64

In [6]:
#making datetime objects
df['webPublicationDate'] = pd.to_datetime(df['webPublicationDate'])
df['webPublicationDate'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 25142 entries, 0 to 25141
Series name: webPublicationDate
Non-Null Count  Dtype
--------------  -----
25142 non-null  datetime64[ns, UTC]
dtypes: datetime64[ns, UTC](1)
memory usage: 196.6 KB

In [7]:
df['webTitle'] = df['webTitle'].str.lower()

THEMES ANALYSIS

In [11]:
#sorting into table so easier to visualise data
uni_section = df.groupby(['university', 'sectionName']).size()
uni_section = uni_section.unstack(fill_value=0)
uni_section.sort_index()
uni_section.head()

sectionName,Activate,Art and design,Australia news,Best of Birmingham,Best practice exchange,Books,Break into tech,Business,Business to business,Cardiff,...,Thinking about money,Travel,UK news,US news,Voluntary Sector Network,Wellness,Women in Leadership,Working in development,World news,Zurich School Competition
university,,,,,,,,,,,,,,,,,,,,,
Cardiff University,0,5,1,0,1,22,0,25,0,135,...,0,3,88,1,2,0,1,1,71,0
Imperial College London,0,17,4,0,0,26,1,67,0,0,...,0,1,75,19,1,0,2,3,608,1
London School of Economics,0,34,8,0,0,104,0,344,1,0,...,1,0,205,21,6,0,1,15,445,0
University College London,0,70,8,0,0,244,0,113,0,1,...,1,4,215,22,2,1,0,5,613,0
University of Birmingham,0,18,2,4,0,19,2,36,0,0,...,0,4,48,5,8,2,1,8,150,0